// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwehlqgjebghfnbrlpgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3ZWhscWdqZWJnaGZuYnJscGdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc0MDA5NTcsImV4cCI6MjA5Mjk3Njk1N30.rYlciyeHHMTgJMEbksjsQOt0cRXXJ8R278oel9BGV4U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});